version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URL: "mongodb://mongo:27017/mydb"
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017
      MONGODB_DBNAME: mydb
      MONGODB_USER: user
      MONGODB_PASSWORD: password
      SECRET_KEY: your_secret_key
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
